# Este archivo es un ejemplo de un archivo docker-compose.yml para ejecutar Tomcat 10.1 con una aplicación web en el contenedor.
# También incluye un contenedor de base de datos MySQL. Puedes personalizarlo según tus necesidades.
# Asegúrate de tener Docker y Docker Compose instalados en tu máquina antes de ejecutar este archivo.

services:
  mysql:
    image: docker.io/bitnami/mysql:8.4
    ports:
      - '3310:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data:
    driver: local 

   